-- Clyvo Care — schema inicial (H2 MODE=Oracle e Oracle FIAP)

CREATE SEQUENCE SQ_CC_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_CC_PET START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_CC_CLINICA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_CC_PRESCRICAO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_CC_LOG_SAUDE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_CC_AGENDAMENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SQ_CC_LOG_SISTEMA START WITH 1 INCREMENT BY 1;

CREATE TABLE TB_CC_USUARIO (
    ID_USUARIO    NUMBER(19)     NOT NULL,
    NOME_USUARIO  VARCHAR2(100)  NOT NULL,
    EMAIL         VARCHAR2(100)  NOT NULL,
    SENHA         VARCHAR2(100)  NOT NULL,
    TP_PERFIL     VARCHAR2(20)   NOT NULL,
    DT_CADASTRO   DATE           NOT NULL,
    CONSTRAINT PK_CC_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_CC_USUARIO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CK_CC_USUARIO_PERFIL CHECK (TP_PERFIL IN ('TUTOR', 'VETERINARIO'))
);

CREATE TABLE TB_CC_PET (
    ID_PET         NUMBER(19)     NOT NULL,
    ID_USUARIO     NUMBER(19)     NOT NULL,
    NOME_PET       VARCHAR2(100)  NOT NULL,
    ESPECIE        VARCHAR2(50)   NOT NULL,
    DT_NASCIMENTO  DATE,
    DT_CADASTRO    DATE           NOT NULL,
    CONSTRAINT PK_CC_PET PRIMARY KEY (ID_PET),
    CONSTRAINT FK_CC_PET_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES TB_CC_USUARIO (ID_USUARIO)
);

CREATE TABLE TB_CC_CLINICA (
    ID_CLINICA    NUMBER(19)     NOT NULL,
    NOME_CLINICA  VARCHAR2(100)  NOT NULL,
    CNPJ          VARCHAR2(14)   NOT NULL,
    ENDERECO      VARCHAR2(200)  NOT NULL,
    TELEFONE      VARCHAR2(15),
    CONSTRAINT PK_CC_CLINICA PRIMARY KEY (ID_CLINICA),
    CONSTRAINT UK_CC_CLINICA_CNPJ UNIQUE (CNPJ)
);

CREATE TABLE TB_CC_PRESCRICAO (
    ID_PRESCRICAO     NUMBER(19)     NOT NULL,
    ID_PET            NUMBER(19)     NOT NULL,
    NOME_MEDICAMENTO  VARCHAR2(100)  NOT NULL,
    DS_DOSAGEM        VARCHAR2(50)   NOT NULL,
    FREQUENCIA_HORAS  NUMBER(3)      NOT NULL,
    DT_INICIO         DATE           NOT NULL,
    DT_FIM            DATE,
    CONSTRAINT PK_CC_PRESCRICAO PRIMARY KEY (ID_PRESCRICAO),
    CONSTRAINT FK_CC_PRESCRICAO_PET FOREIGN KEY (ID_PET) REFERENCES TB_CC_PET (ID_PET),
    CONSTRAINT CK_CC_PRESCRICAO_FREQ CHECK (FREQUENCIA_HORAS >= 1)
);

CREATE TABLE TB_CC_LOG_SAUDE (
    ID_LOG       NUMBER(19)     NOT NULL,
    ID_PET       NUMBER(19)     NOT NULL,
    DT_REGISTRO  TIMESTAMP      NOT NULL,
    VL_METRICA   NUMBER(10, 2)  NOT NULL,
    METRICA      VARCHAR2(30)   NOT NULL,
    OBS          VARCHAR2(255),
    CONSTRAINT PK_CC_LOG_SAUDE PRIMARY KEY (ID_LOG),
    CONSTRAINT FK_CC_LOG_SAUDE_PET FOREIGN KEY (ID_PET) REFERENCES TB_CC_PET (ID_PET)
);

CREATE TABLE TB_CC_AGENDAMENTO (
    ID_AGENDAMENTO  NUMBER(19)     NOT NULL,
    ID_PET          NUMBER(19)     NOT NULL,
    ID_CLINICA      NUMBER(19)     NOT NULL,
    DT_AGENDA       TIMESTAMP      NOT NULL,
    TIPO_SERVICO    VARCHAR2(50)   NOT NULL,
    STATUS          VARCHAR2(20)   NOT NULL,
    CONSTRAINT PK_CC_AGENDAMENTO PRIMARY KEY (ID_AGENDAMENTO),
    CONSTRAINT FK_CC_AGENDAMENTO_PET FOREIGN KEY (ID_PET) REFERENCES TB_CC_PET (ID_PET),
    CONSTRAINT FK_CC_AGENDAMENTO_CLINICA FOREIGN KEY (ID_CLINICA) REFERENCES TB_CC_CLINICA (ID_CLINICA),
    CONSTRAINT CK_STATUS_AGENDAMENTO CHECK (STATUS IN ('AGENDADO', 'CONCLUIDO', 'CANCELADO'))
);

CREATE TABLE TB_CC_LOG_SISTEMA (
    ID_ERRO       NUMBER(19)     NOT NULL,
    NOME_PROC     VARCHAR2(100)  NOT NULL,
    NOME_USUARIO  VARCHAR2(100),
    DT_ERRO       DATE           NOT NULL,
    CD_ERRO       NUMBER(5)      NOT NULL,
    MSG_ERRO      VARCHAR2(400)  NOT NULL,
    CONSTRAINT PK_CC_LOG_SISTEMA PRIMARY KEY (ID_ERRO)
);
