-- Cargas iniciais. Senhas em texto puro são recodificadas para BCrypt na subida da aplicação.

INSERT INTO TB_CC_USUARIO (ID_USUARIO, NOME_USUARIO, EMAIL, SENHA, TP_PERFIL, DT_CADASTRO)
VALUES (SQ_CC_USUARIO.NEXTVAL, 'Maria Silva', 'maria@email.com', 'senha123', 'TUTOR', CURRENT_DATE);

INSERT INTO TB_CC_USUARIO (ID_USUARIO, NOME_USUARIO, EMAIL, SENHA, TP_PERFIL, DT_CADASTRO)
VALUES (SQ_CC_USUARIO.NEXTVAL, 'Carlos Mendes', 'carlos.vet@clyvo.com', 'senha123', 'VETERINARIO', CURRENT_DATE);

INSERT INTO TB_CC_PET (ID_PET, ID_USUARIO, NOME_PET, ESPECIE, DT_NASCIMENTO, DT_CADASTRO)
SELECT SQ_CC_PET.NEXTVAL, u.ID_USUARIO, 'Thor', 'Cachorro', DATE '2020-05-10', CURRENT_DATE
FROM TB_CC_USUARIO u
WHERE u.EMAIL = 'maria@email.com';

INSERT INTO TB_CC_PET (ID_PET, ID_USUARIO, NOME_PET, ESPECIE, DT_NASCIMENTO, DT_CADASTRO)
SELECT SQ_CC_PET.NEXTVAL, u.ID_USUARIO, 'Luna', 'Gato', DATE '2022-02-14', CURRENT_DATE
FROM TB_CC_USUARIO u
WHERE u.EMAIL = 'maria@email.com';

INSERT INTO TB_CC_CLINICA (ID_CLINICA, NOME_CLINICA, CNPJ, ENDERECO, TELEFONE)
VALUES (SQ_CC_CLINICA.NEXTVAL, 'Clinica Pet Care', '12345678000199', 'Av. Paulista, 1000', '11999999999');

INSERT INTO TB_CC_PRESCRICAO (ID_PRESCRICAO, ID_PET, NOME_MEDICAMENTO, DS_DOSAGEM, FREQUENCIA_HORAS, DT_INICIO, DT_FIM)
SELECT SQ_CC_PRESCRICAO.NEXTVAL, p.ID_PET, 'Vermifugo', '1 comprimido', 24, CURRENT_DATE, CURRENT_DATE + 7
FROM TB_CC_PET p
WHERE p.NOME_PET = 'Thor';

INSERT INTO TB_CC_LOG_SAUDE (ID_LOG, ID_PET, DT_REGISTRO, VL_METRICA, METRICA, OBS)
SELECT SQ_CC_LOG_SAUDE.NEXTVAL, p.ID_PET, CURRENT_TIMESTAMP, 12.40, 'peso', 'Controle rotineiro de peso'
FROM TB_CC_PET p
WHERE p.NOME_PET = 'Thor';

INSERT INTO TB_CC_LOG_SAUDE (ID_LOG, ID_PET, DT_REGISTRO, VL_METRICA, METRICA, OBS)
SELECT SQ_CC_LOG_SAUDE.NEXTVAL, p.ID_PET, CURRENT_TIMESTAMP, 250, 'alimentacao', 'Racao diaria em gramas'
FROM TB_CC_PET p
WHERE p.NOME_PET = 'Thor';

INSERT INTO TB_CC_AGENDAMENTO (ID_AGENDAMENTO, ID_PET, ID_CLINICA, DT_AGENDA, TIPO_SERVICO, STATUS)
SELECT SQ_CC_AGENDAMENTO.NEXTVAL, p.ID_PET, c.ID_CLINICA, TIMESTAMP '2026-09-20 14:00:00', 'Consulta', 'AGENDADO'
FROM TB_CC_PET p
CROSS JOIN TB_CC_CLINICA c
WHERE p.NOME_PET = 'Thor'
  AND c.CNPJ = '12345678000199';
